## Solving Two Sets of Linear Equations with different priority
The objective of this exercise is to solve a system of linear equations with different priorities (one set of equations has to have zero error, while the error on the other set of equations has to be minimized) 

##### We have the following equation:
$y = ax_1 + bx_2 + cx_3$ (1)

that relates the variable $y$ to the variable $x_1,x_2,x_3$, where $a, b, \text{and} ~ c$ are unknown constants and we want to find them. 




### 1. First Dataset

Data 1: $x_1 = 0.54, x_2 = 0.12, x_3 = 0.56, y = 4.9, $

Data 2: $x_1 = 0.93, x_2 = 0.93, x_3 = 0.11, y = 7.06, $


##### Question 1: Find the constants $a, b, \text{and} ~ c$ such that the equation (1) is satisfied on the first dataset. (hint: form a linear equation XA = Y where A is the vector of the constants $a, b, \text{and} ~ c$). 
##### Question 2: Find the nullspace of $X$ and obtain several different values of the constants $a, b, \text{and} ~ c$ that still satisfies the equation (1) perfectly (i.e. the error is zero).

### 2. Second Dataset

Data 1: $x_1 = 0.17, x_2 = 0.95, x_3 = 0.99, y = 7.15 $

Data 2: $x_1 = 0.01, x_2 = 0.79, x_3 = 0.48, y = 4.31 $


##### Question 3: Using the constants  $a, b, \text{and} ~ c$ obtained in Question 1, compute the error of the equation (1) w.r.t. the second dataset

##### Question 4: Find the constants $a, b, \text{and} ~ c$ that minimizes the error of the equation (1) on the second dataset, while still perfectly satisfying the equation (1) on the first dataset. (Hint: use the nullspace of $X$)

### Solution 

In [2]:
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
from numpy.linalg import inv,pinv
from numpy import dot,power
from utils import *

In [156]:
#A1_true = np.array([3.,4.,5.])[:,None]
#X = np.random.rand(2,3)
#Y = dot(X,A1_true)
X1 = np.array([[0.54,0.12,0.56],[0.93,0.93,0.11]])
Y1 = np.array([4.9,7.06])[:,None]
print X1,Y1

[[0.54 0.12 0.56]
 [0.93 0.93 0.11]] [[4.9 ]
 [7.06]]


In [157]:
A1 = dot(pinv(X1),Y1)
N1 = np.eye(3) - dot(pinv(X1),X1)

#### Second System 

In [158]:
#A2_true = np.array([2.,3.,4.])[:,None]
#X2 = np.random.rand(2,3)
#Y2 = dot(X2,A2_true)
X2 = np.array([[0.17, 0.95, 0.99],[0.01, 0.79, 0.48]])
Y2 = np.array([7.15, 4.31])[:,None]
print X2
print Y2

[[0.17 0.95 0.99]
 [0.01 0.79 0.48]]
[[7.15]
 [4.31]]


In [159]:
A2 = np.dot(pinv(np.dot(X2,N1),rcond=1e-7),Y2-np.dot(X2,A1))
A = A1 + np.dot(N1,A2)

#### Error using the nullspace 

In [161]:
#error to first system
print np.dot(X1,A)-Y1

#error to second system
print np.linalg.norm(np.dot(X2,A)-Y2)

[[3.55271368e-15]
 [0.00000000e+00]]
0.22675198765518928


#### Error using only the first equation

In [162]:
#error to first system
print np.dot(X1,A1)-Y1

#error to second system
print np.linalg.norm(np.dot(X2,A1)-Y2)

[[ 3.55271368e-15]
 [-8.88178420e-16]]
0.927700257943241


#### Error using the whole equation 

In [163]:
X = np.vstack([X1,X2])
Y = np.vstack([Y1,Y2])
A3 = dot(pinv(X,rcond=1e-7),Y)
#error to first system
print np.dot(X1,A3)-Y1

#error to second system
print np.linalg.norm(np.dot(X2,A3)-Y2)

[[-0.07538118]
 [ 0.02429501]]
0.194502718655885
